# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Work Hard, Span Easy
description: >- # this means to ignore newlines until "baseurl:"
  Parallelizing things is easy, but making them fast is hard.
  A blog about parallel algorithms, data structures,
  programming languages, and anything else that comes to mind.
  Written by Sam Westrick.
# the subpath of your site, e.g. /blog
baseurl: ""
# the base hostname & protocol for your site, e.g. http://example.com
url: "https://shwestrick.github.io"

minima:
  # generate social links in footer
  social_links:
    github: shwestrick
    stackoverflow:
      link: "1031831"
      text: sam-westrick
    youtube: SamWestrick

# Build settings
theme: minima
plugins:
  - jekyll-feed
  - jemoji

kramdown:
  parse_block_html: true

staticman_url: https://shwestrick-github-io-staticman.herokuapp.com/v2/entry/shwestrick/shwestrick.github.io/master/comments

reCaptcha:
  siteKey: 6LeGsLgZAAAAAGoPDkVoty5M4b47BaXTzMYR2mDa
  secret: GsSgGpWLcx59qo1AMjWvzDOCReP1himiEbHj+q+2eFEcnratWCmiQ8tQYyhf111llZhHQOE0abuOFHHQzCHuzghCTn7RMsb4aDkCOuklQeooN9Kps3QrOjmP5DWB2xkQkEfEgDEpsfDEow9LBGuWUJKkrNR/tzhwcrV1dbzwAt9yEyMcaH50qRufgV+ED+bGy1HkH+AJG0aBWJYaMznWltZofiV6bBLLshDPuatB5+3iud1wrkTMLrZ8VSxbKVNYtq7iQS4dhOFR+UyDZ5xPS5dT4mXXmCpSYx+65Ds2kAKQuOBzDxypPSJ3nTluP6rDlSl5d8l+HeY+paLm5sH6ssOvcAlGJ+DwOVEf1bkPyerG54uRPmSyZm0vrMYKghPa5QLXEfBmgWHqoExScFG1zYBmBOIBE0K2GKaE7fgSivIPfVabx2DVXN+dn2dcmLjD9HTNTsASSEYpPDyN/sqQMByv9WRm2fKXRTw4H2g86MHnZ/jrXGqVHxfz63dU8hmLLLYUvCLT9oYJb+l6bFde7LEhPB8D0tvn3qiknegp7N/BwcE7YLQkIVdaqBaqaSM046ZM0LMtKeBeVfDtXQvLa4v/X8MAySgsHUW+dl03chR61i8jwB6nHXMELO/KczJcxK1ejfmG1xtNm/BQKTOiH0JV/3S0qjtheUNWkrq9rpU=


# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
